### ISSUE TITLE
Claim takeover not updated / wrong claim showing controlling

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/chainquery#108]
![image](https://user-images.githubusercontent.com/8120721/54781661-3fbd0880-4bf3-11e9-8007-479da364da6e.png)

https://traction.lbry.io/question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7InF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6Mjk4LCJmaWx0ZXIiOlsiYW5kIixbIj0iLFsiZmllbGQtaWQiLDczOTZdLCJwaXhlbGJvYXJkLTMweDMwIl1dfSwidHlwZSI6InF1ZXJ5IiwiZGF0YWJhc2UiOjZ9LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=

```C:\Users\thoma\Desktop>lbrynet claim list pixelboard-30x30
{
  "claims": [
    {
      "address": "bTowZtMWUjj2bvt1xLhyrMoJzVhYyRBHph",
      "amount": "200.0",
      "claim_id": "9aa74a4a3bbdbaa7628440fbeab56f57ef38b0de",
      "claim_sequence": 2,
      "decoded_claim": true,
      "depth": 478,
      "effective_amount": "200.0",
      "has_signature": false,
      "height": 537896,
      "hex": "080110011a6f08011227080410011a0753544f4c454e21220842414841484148412a0032044e6f6e6538004a0052005a001a42080110011a30e308cd49f6a6e840247a124daf4e85a42f412bb992a2f0739903130aea2746e271462ce3302c5709f5b93a24ae4df1d4220a696d6167652f6a706567",
      "name": "pixelboard-30x30",
      "nout": 0,
      "permanent_url": "pixelboard-30x30#9aa74a4a3bbdbaa7628440fbeab56f57ef38b0de",
      "supports": [],
      "txid": "979c39aa7f771352f6105b20ab21f0e2765d931a4f427241df143ec622eb6cb9",
      "valid_at_height": 537896,
      "value": {
        "claimType": "streamType",
        "stream": {
          "metadata": {
            "author": "",
            "description": "BAHAHAHA",
            "language": "en",
            "license": "None",
            "licenseUrl": "",
            "nsfw": false,
            "preview": "",
            "thumbnail": "",
            "title": "STOLEN!",
            "version": "_0_1_0"
          },
          "source": {
            "contentType": "image/jpeg",
            "source": "e308cd49f6a6e840247a124daf4e85a42f412bb992a2f0739903130aea2746e271462ce3302c5709f5b93a24ae4df1d4",
            "sourceType": "lbry_sd_hash",
            "version": "_0_0_1"
          },
          "version": "_0_0_1"
        },
        "version": "_0_0_1"
      }
    },
    {
      "address": "bS5AY4eP7aKvwcRAuCf6sh7FuWZBC6Lmwj",
      "amount": "220.0",
      "claim_id": "efcc720eb006ac49acb0399528f937d8fd107670",
      "claim_sequence": 1,
      "decoded_claim": true,
      "depth": 255,
      "effective_amount": "220.0",
      "has_signature": false,
      "height": 538119,
      "hex": "080110011a6d08011226080410011a072366666666303022074d494e452121212a0032044e6f6e6538004a0052005a001a41080110011a305ea471f20ff761267158da533b1c3974a85ddec92a751bb6cf0e30ac35de61e7259d8b4300091baded678db0f1bfed8c2209696d6167652f706e67",
      "name": "pixelboard-30x30",
      "nout": 0,
      "permanent_url": "pixelboard-30x30#efcc720eb006ac49acb0399528f937d8fd107670",
      "supports": [],
      "txid": "a11c8b246d00959248a793ad8dded0195e06c4968137dd72003e72196217c0f1",
      "valid_at_height": 538125,
      "value": {
        "claimType": "streamType",
        "stream": {
          "metadata": {
            "author": "",
            "description": "MINE!!!",
            "language": "en",
            "license": "None",
            "licenseUrl": "",
            "nsfw": false,
            "preview": "",
            "thumbnail": "",
            "title": "#ffff00",
            "version": "_0_1_0"
          },
          "source": {
            "contentType": "image/png",
            "source": "5ea471f20ff761267158da533b1c3974a85ddec92a751bb6cf0e30ac35de61e7259d8b4300091baded678db0f1bfed8c",
            "sourceType": "lbry_sd_hash",
            "version": "_0_0_1"
          },
          "version": "_0_0_1"
        },
        "version": "_0_0_1"
      }
    }
  ],
  "last_takeover_height": 538125,
  "normalized_name": "pixelboard-30x30",
  "supports_without_claims": []
}
```

**Comment by tzarebczan** [comment]
This also affects the lbry://404 claim.

**Comment by kauffj** [comment]
This is marked in progress on zenhub, is that actually the case @tiger5226 ?

**Comment by tiger5226** [comment]
At one point it was. I deployed changes to improve this problem but we still found it happening just less often, so I did not close it. I will set it correctly.

**Comment by tiger5226** [comment]
Ok, I am pretty certain I figured out how this was happening. It was the result of some claims not being marked as spent so the takeover wasn't taking over. I am going to leave it open for now because I want to create a test case for it so I can validate.

**Comment by tzarebczan** [comment]
This is still happening - recently had a claim takeover on @saltycracker and it was not reflected in CQ.

**Comment by tzarebczan** [comment]
This is still happening. Can we at least have some job setup to fix them automatically if we can't find the root cause?
